apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmi-reader
rules:
  - apiGroups: 
    - kubevirt.io
    resources:
      - virtualmachineinstances
    verbs:
      - list
      - watch
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmi-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmi-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: aap
