- name: Listen for Machine resource events
  hosts: localhost

  sources:
  - sabre1041.eda.k8s:
      api_version: kubevirt.io/v1
      kind: VirtualMachineInstance
      namespace: kubevirt-gitops

  rules:
    - name: Run Job on VM start
      condition: 
        all:
        - event.type == 'MODIFIED'
        - event.resource.status.phase == 'Running'
      action:
        run_job_template:
          name: deploy_object_detection_model 
          organization: codell.io 
        debug:
